# Default paths on private servers
default:
  data_dir: "/data/unixhome/jdoe/data/misc_project"
  private_data_dir: "/data/unixhome/jdoe/private_data/misc_project"
  output_dir: "/data/unixhome/jdoe/GitRepositories/INT_misc_project/output"

# Alternative paths on AWS servers
AWS:
  data_dir: "/data/awshomes/jdoe/data/misc_project"
  private_data_dir: "/data/awshomes/jdoe/private_data/misc_project"
  output_dir: "/data/awshomes/jdoe/GitRepositories/INT_misc_project/output"


# Alternative paths on local machine.
local:
  data_dir: "H:/My Documents/OFR_work/data/misc_project"
  private_data_dir: "H:/My Documents/OFR_work/private_data/misc_project"
  output_dir: "C:/Users/jdoe/GitRepositories/INT_misc_project/output"
